import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { brand } from "@mytownapp/design";
import { Screen } from "@/components/screen";
import { useAuth } from "@/providers/auth-provider";
import { useFeed } from "@/providers/feed-provider";

export default function Account(){
  const auth=useAuth();const {town}=useFeed();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);
  const submit=async(mode:"in"|"up")=>{setBusy(true);try{if(mode==="in")await auth.signIn(email,password);else Alert.alert("Account",await auth.signUp(email,password));}catch(error){Alert.alert("Account",error instanceof Error?error.message:"Please try again.");}finally{setBusy(false)}};
  if(auth.loading)return <Screen><Text style={s.body}>Loading your account…</Text></Screen>;
  return <Screen><Text style={s.kicker}>MYTOWNAPP</Text><Text style={s.h1}>Your account</Text>{auth.userId?<><View style={s.profile}><View style={s.avatar}><Text style={s.initials}>{auth.email?.slice(0,2).toUpperCase()}</Text></View><View style={s.copy}><Text style={s.name}>Welcome back</Text><Text style={s.body}>{auth.email}</Text><Text style={s.body}>Primary town: {town?.name??"Not selected"}</Text></View></View><Pressable style={s.button} disabled={busy} onPress={()=>void auth.signOut().catch(error=>Alert.alert("Account",error.message))}><Text style={s.buttonText}>Sign out</Text></Pressable></>:<><Text style={s.intro}>Sign in to save businesses, offers, and your preferred town.</Text><TextInput style={s.input} autoCapitalize="none" autoComplete="email" keyboardType="email-address" placeholder="Email address" value={email} onChangeText={setEmail}/><TextInput style={s.input} autoCapitalize="none" placeholder="Password" secureTextEntry value={password} onChangeText={setPassword}/><Pressable style={[s.button,busy&&s.disabled]} disabled={busy} onPress={()=>void submit("in")}><Text style={s.buttonText}>{busy?"Please wait…":"Sign in"}</Text></Pressable><Pressable style={s.secondary} disabled={busy} onPress={()=>void submit("up")}><Text style={s.secondaryText}>Create an account</Text></Pressable></>}</Screen>;
}
const s=StyleSheet.create({kicker:{fontSize:10,letterSpacing:2,fontWeight:"900",color:brand.colors.green,marginTop:12},h1:{fontSize:34,fontWeight:"700",color:brand.colors.ink},intro:{color:brand.colors.muted,lineHeight:21,marginVertical:22},profile:{flexDirection:"row",alignItems:"center",gap:14,marginVertical:24,padding:18,backgroundColor:"white",borderRadius:18,borderWidth:1,borderColor:brand.colors.line},avatar:{width:58,height:58,borderRadius:18,alignItems:"center",justifyContent:"center",backgroundColor:brand.colors.mint},initials:{fontWeight:"900",color:brand.colors.green},copy:{flex:1},name:{fontSize:18,fontWeight:"700",color:brand.colors.ink},body:{color:brand.colors.muted,marginTop:4},input:{height:52,backgroundColor:"white",borderWidth:1,borderColor:brand.colors.line,borderRadius:14,paddingHorizontal:15,marginBottom:12,fontSize:16},button:{height:52,backgroundColor:brand.colors.green,borderRadius:14,alignItems:"center",justifyContent:"center",marginTop:8},buttonText:{color:"white",fontWeight:"800"},secondary:{height:52,alignItems:"center",justifyContent:"center"},secondaryText:{color:brand.colors.green,fontWeight:"800"},disabled:{opacity:.55}});
