import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ChevronDown, Heart, Search } from "lucide-react-native";
import { brand } from "@mytownapp/design";
import { Screen } from "@/components/screen";
import { useFeed } from "@/providers/feed-provider";

export default function HomeScreen(){
  const feed=useFeed();
  const [query,setQuery]=useState("");
  const normalizedQuery=query.trim().toLowerCase();
  const businesses=normalizedQuery?feed.businesses.filter(item=>`${item.name} ${item.category} ${item.description}`.toLowerCase().includes(normalizedQuery)):feed.businesses;
  const cycleTown=()=>{if(!feed.town||feed.towns.length<2)return;const index=feed.towns.findIndex(x=>x.id===feed.town?.id);void feed.selectTown(feed.towns[(index+1)%feed.towns.length].id).catch(showError)};
  return <Screen>
    <Text style={s.kicker}>EXPLORE</Text><Pressable style={s.town} onPress={cycleTown}><Text style={s.h1}>{feed.town?.name??"My town"}</Text><ChevronDown color={brand.colors.green}/></Pressable>
    <View style={s.search}><Search color={brand.colors.muted} size={20}/><TextInput accessibilityLabel="Search local businesses" style={s.searchInput} placeholder="Search local businesses" placeholderTextColor={brand.colors.muted} value={query} onChangeText={setQuery}/></View>
    <View style={s.section}><Text style={s.heading}>Made for your town</Text><Text style={s.link}>{feed.loading?"Loading…":`${businesses.length} local`}</Text></View>
    {!feed.loading&&businesses.length===0&&<Text style={s.body}>{normalizedQuery?"No businesses match your search.":"No published businesses yet. Check back soon."}</Text>}
    {businesses.map(business=>{const favorite=feed.favoriteIds.includes(business.id);const offer=feed.offers.find(x=>x.businessId===business.id);const redeemed=offer&&feed.redeemedOfferIds.includes(offer.id);return <View style={s.card} key={business.id}><View style={s.image}><Text style={s.letter}>{business.name[0]}</Text><Pressable accessibilityLabel={`${favorite?"Remove":"Save"} ${business.name}`} style={s.heart} onPress={()=>void feed.toggleFavorite(business.id).catch(showError)}><Heart color={brand.colors.ink} fill={favorite?brand.colors.coral:"transparent"} size={19}/></Pressable></View><View style={s.cardBody}><Text style={s.category}>{business.category.toUpperCase()}</Text><Text style={s.cardTitle}>{business.name}</Text><Text style={s.body}>{business.description}</Text><Text style={s.address}>{business.address}</Text>{offer&&<View style={s.offer}><Pressable onPress={()=>void feed.toggleSave(offer.id).catch(showError)}><Text style={s.offerLabel}>{feed.savedOfferIds.includes(offer.id)?"SAVED OFFER":"LOCAL OFFER"}</Text><Text style={s.offerTitle}>{offer.title}</Text><Text style={s.body}>{offer.description}</Text></Pressable><Pressable disabled={redeemed} style={[s.redeem,redeemed&&s.redeemed]} onPress={()=>confirmRedemption(offer.id,offer.title,feed.redeem)}><Text style={s.redeemText}>{redeemed?"Redeemed":"Redeem in store"}</Text></Pressable></View>}</View></View>})}
    <View style={s.section}><Text style={s.heading}>Coming up</Text><Text style={s.link}>Calendar</Text></View>
    {feed.events.slice(0,1).map(event=><View style={s.event} key={event.id}><View style={s.date}><Text style={s.month}>{new Date(event.startsAt).toLocaleDateString("en-US",{month:"short"}).toUpperCase()}</Text><Text style={s.day}>{new Date(event.startsAt).getDate()}</Text></View><View><Text style={s.cardTitle}>{event.title}</Text><Text style={s.body}>{event.venue}</Text></View></View>)}
  </Screen>;
}
function showError(error:Error){Alert.alert("mytownapp",error.message)}
function confirmRedemption(offerId:string,title:string,redeem:(offerId:string)=>Promise<void>){Alert.alert("Redeem this offer?",`${title}\n\nOnly confirm when a staff member is ready to accept it.`,[{text:"Not yet",style:"cancel"},{text:"Confirm",onPress:()=>void redeem(offerId).then(()=>Alert.alert("Offer redeemed","Show this confirmation to the business.")).catch(showError)}])}
const s=StyleSheet.create({kicker:{fontSize:10,letterSpacing:2,fontWeight:"900",color:brand.colors.green,marginTop:12},town:{flexDirection:"row",alignItems:"center",gap:5},h1:{fontSize:34,fontWeight:"700",color:brand.colors.ink},search:{height:50,backgroundColor:"white",borderRadius:15,flexDirection:"row",alignItems:"center",gap:11,paddingHorizontal:15,borderWidth:1,borderColor:brand.colors.line,marginTop:20},searchInput:{flex:1,color:brand.colors.ink,fontSize:15},section:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:28,marginBottom:13},heading:{fontSize:22,fontWeight:"700",color:brand.colors.ink},link:{fontSize:13,fontWeight:"800",color:brand.colors.green},card:{backgroundColor:"white",borderRadius:20,overflow:"hidden",marginBottom:16,borderWidth:1,borderColor:brand.colors.line},image:{height:150,alignItems:"center",justifyContent:"center",backgroundColor:brand.colors.mint},letter:{fontSize:70,fontWeight:"800",color:brand.colors.green,opacity:.45},heart:{position:"absolute",right:12,top:12,width:38,height:38,borderRadius:19,backgroundColor:"white",alignItems:"center",justifyContent:"center"},cardBody:{padding:17},category:{fontSize:9,letterSpacing:1.4,fontWeight:"900",color:brand.colors.green},cardTitle:{fontSize:20,fontWeight:"700",color:brand.colors.ink,marginTop:4},body:{color:brand.colors.muted,lineHeight:20,marginTop:4},address:{color:brand.colors.green,fontWeight:"700",marginTop:8},offer:{backgroundColor:brand.colors.cream,borderRadius:13,padding:12,marginTop:14},offerLabel:{fontSize:9,letterSpacing:1.2,fontWeight:"900",color:brand.colors.coral},offerTitle:{fontWeight:"700",color:brand.colors.ink,marginTop:3},redeem:{height:42,borderRadius:12,backgroundColor:brand.colors.green,alignItems:"center",justifyContent:"center",marginTop:12},redeemed:{backgroundColor:brand.colors.muted},redeemText:{color:"white",fontWeight:"800"},event:{flexDirection:"row",alignItems:"center",gap:14,backgroundColor:"white",borderWidth:1,borderColor:brand.colors.line,padding:14,borderRadius:17},date:{width:48,height:54,alignItems:"center",justifyContent:"center",backgroundColor:brand.colors.mint,borderRadius:12},month:{fontSize:9,fontWeight:"900",color:brand.colors.green},day:{fontSize:22,fontWeight:"800",color:brand.colors.ink}});
